version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: brokerx-postgres
    environment:
      POSTGRES_DB: brokerx_orders
      POSTGRES_USER: brokerx
      POSTGRES_PASSWORD: monsecret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - brockerx-net

  redis:
    image: redis:latest
    container_name: brokerx-redis
    ports:
      - "6378:6379"
    networks:
      - brockerx-net

  order-service:
    build: .
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/brokerx_orders
      SPRING_DATASOURCE_USERNAME: brokerx
      SPRING_DATASOURCE_PASSWORD: monsecret
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - brockerx-net

volumes:
  postgres_data:

networks:
  brockerx-net:
    external: true
